#include <fuzzer/types/int_type.h>

using namespace std;

const uint64_t specialInts[specIntsLen] = {0ULL,
                                           1ULL,
                                           2ULL,
                                           31ULL,
                                           32ULL,
                                           33ULL,
                                           63ULL,
                                           64ULL,
                                           65ULL,
                                           127ULL,
                                           128ULL,
                                           129ULL,
                                           255ULL,
                                           256ULL,
                                           257ULL,
                                           511ULL,
                                           512ULL,
                                           1023ULL,
                                           1024ULL,
                                           1025ULL,
                                           2047ULL,
                                           2048ULL,
                                           2049ULL,
                                           4095ULL,
                                           4096ULL,
                                           4097ULL,
                                           (1ULL << 15) - 1,
                                           (1ULL << 15),
                                           (1ULL << 15) + 1,
                                           (1ULL << 16) - 1,
                                           (1ULL << 16),
                                           (1ULL << 16) + 1,
                                           (1ULL << 31) - 1,
                                           (1ULL << 31),
                                           (1ULL << 31) + 1,
                                           (1ULL << 32) - 1,
                                           (1ULL << 32),
                                           (1ULL << 32) + 1,
                                           (1ULL << 63) - 1,
                                           (1ULL << 63),
                                           (1ULL << 63) + 1,
                                           0xFFFFFFFFFFFFFFFFULL};
